<script setup lang="ts">
import { ref, computed } from 'vue'
import { Plus, Minus, ArrowUpRight } from 'lucide-vue-next'
import PageHeading from '../components/PageHeading.vue'
import { faq } from '../data/faq'
import { catalogUrl } from '../data/site'
const query=ref('');const opened=ref<number|null>(0)
const filtered=computed(()=>faq.map((item,index)=>({...item,index})).filter(item=>(item.q+' '+item.a).toLocaleLowerCase('id').includes(query.value.toLocaleLowerCase('id').trim())))
</script>
<template><PageHeading label="PERTANYAAN UMUM" number="05 / INFORMASI" title="Lebih jelas di awal." accent="Lebih tenang kemudian." description="Tentang fitur, biaya, data, dan proses implementasi. Kami rangkum hal yang perlu Anda ketahui sebelum memilih sistem."/><div class="faq-layout wrap"><aside class="faq-aside"><h3>Masih ada pertanyaan?</h3><p>Ceritakan kebutuhan spesifik percetakan Anda.</p><RouterLink to="/kontak" class="text-link">Konsultasikan kebutuhan <ArrowUpRight :size="17"/></RouterLink><a :href="catalogUrl" target="_blank" rel="noopener" class="text-link" style="margin-top:15px">Baca katalog 2026 <ArrowUpRight :size="17"/></a></aside><section aria-label="Daftar pertanyaan"><label class="screen-reader-only" for="faq-search">Cari pertanyaan</label><input id="faq-search" class="faq-search" type="search" v-model="query" placeholder="Cari pertanyaan, misalnya: biaya atau stok"/><p class="screen-reader-only" aria-live="polite">{{filtered.length}} pertanyaan ditemukan</p><article v-for="item in filtered" :key="item.index" class="faq-item"><h2 style="font:inherit"><button :id="'question-'+item.index" :aria-expanded="opened===item.index" :aria-controls="'answer-'+item.index" @click="opened=opened===item.index?null:item.index">{{item.q}}<Minus v-if="opened===item.index" :size="19"/><Plus v-else :size="19"/></button></h2><div v-show="opened===item.index" :id="'answer-'+item.index" role="region" :aria-labelledby="'question-'+item.index" class="faq-answer">{{item.a}}</div></article><p v-if="!filtered.length" class="no-results">Belum ada pertanyaan yang cocok. Coba kata lain atau hubungi tim melalui halaman konsultasi.</p></section></div></template>
