<script setup lang="ts">
import { Receipt, Calculator, Users, Boxes, ChartNoAxesCombined, ShieldCheck, ClipboardCheck, ShoppingCart, Building2, History, Layers, PanelsTopLeft, Printer, ClipboardList, Clock, GitCompareArrows, Network, Sparkles, ArrowUpRight } from 'lucide-vue-next'
import type { Component } from 'vue'
import { modules } from '../data/features'
import PageHeading from '../components/PageHeading.vue'
import CtaSection from '../components/CtaSection.vue'
const icons: Record<string,Component> = { Receipt, Calculator, Users, Boxes, ChartNoAxesCombined, ShieldCheck, ClipboardCheck, ShoppingCart, Building2, History, Layers, PanelsTopLeft, Printer, ClipboardList, Clock, GitCompareArrows, Network }
</script>
<template><PageHeading label="FITUR & MODUL" number="01 / PRODUK" title="Satu sistem." accent="Seluruh operasional." description="Mulai dari fondasi yang lengkap. Tambahkan modul sesuai tantangan yang benar-benar ingin Anda selesaikan."/>
<nav class="tab-bar wrap" aria-label="Pilih modul"><a v-for="item in modules" :href="'#'+item.id" :key="item.id">{{item.id === 'inti' ? 'Modul Inti' : 'Pack '+item.id.charAt(0).toUpperCase()+item.id.slice(1)}}</a><a href="#ai">AI Tutor & Analis</a></nav>
<section v-for="item in modules" :key="item.id" :id="item.id" class="module-section wrap"><div class="split"><div class="module-summary"><p class="eyebrow">{{item.number}} — {{item.id.toUpperCase()}}</p><h2>{{item.name}}</h2><span class="module-tag">{{item.tag}}</span><p>{{item.description}}</p><RouterLink to="/harga" class="text-link">Lihat paket & harga <ArrowUpRight :size="17"/></RouterLink><div v-if="item.note" class="notice">{{item.note}}</div></div><div class="feature-list"><article v-for="feature in item.items" :key="feature[0]"><component :is="icons[feature[2]!]" :size="25" :stroke-width="1.25"/><h3>{{feature[0]}}</h3><p>{{feature[1]}}</p></article></div></div></section>
<section id="ai" class="ai-section"><div class="wrap"><p class="eyebrow"><Sparkles :size="17"/> KECERDASAN BUATAN</p><h2>Dua AI.<br/>Dua pekerjaan yang berbeda.</h2><div class="ai-grid"><article><span class="module-tag">TERMASUK DI SEMUA PAKET</span><h3>AI Tutor</h3><p>Asisten yang membantu Anda dan tim memakai aplikasi. Memahami halaman yang sedang dibuka, menjawab pertanyaan cara pakai, dan membantu karyawan baru lebih cepat mandiri.</p><span class="micro">PANDUAN PENGGUNAAN · TANPA MEMOTONG KUOTA SUPPORT</span></article><article><span class="module-tag">TAMBAHAN OPSIONAL · RP4.000.000 / TAHUN</span><h3>AI Analis</h3><p>Tanya soal omzet, HPP, laba, stok, produksi, dan piutang dari data percetakan Anda sendiri. Membantu owner membaca kondisi usaha tanpa membuka banyak laporan satu per satu.</p><span class="micro">ANALISIS USAHA · UNTUK PEMILIK BISNIS</span></article></div></div></section><CtaSection/></template>
