<script setup lang="ts">
import { ArrowUpRight, ArrowRight, ClipboardList, Printer, Boxes, ChartNoAxesCombined } from 'lucide-vue-next'
import ArrowLink from '../components/ArrowLink.vue'
import CtaSection from '../components/CtaSection.vue'
const pillars = [{ icon: ClipboardList, name: 'Order tercatat.', text: 'Detail pesanan, harga, dan deadline ada di satu tempat.' }, { icon: Printer, name: 'Produksi terpantau.', text: 'Tim tahu apa yang dikerjakan dan sampai mana prosesnya.' }, { icon: Boxes, name: 'Stok terkendali.', text: 'Pemakaian bahan ikut tercatat saat produksi berjalan.' }, { icon: ChartNoAxesCombined, name: 'Angka lebih jelas.', text: 'Pahami HPP, laba per order, dan arus uang bisnis Anda.' }]
</script>
<template>
  <section class="hero wrap">
    <div class="hero-copy"><p class="eyebrow"><span class="tiny-square"></span>KHUSUS BISNIS PERCETAKAN</p><h1>Percetakan<br/>Lebih <span class="highlight">Rapi.</span><br/>Lebih Terkontrol.</h1><p class="hero-description">Dari order, produksi, stok, hingga laporan.<br class="desktop-break"/> Grafika Pro menyatukan operasional percetakan Anda dalam satu sistem.</p><div class="actions"><ArrowLink/><RouterLink to="/cara-kerja" class="text-link">Lihat Cara Kerja <ArrowRight :size="18"/></RouterLink></div><div class="hero-footnote"><span class="rule"></span><span>Untuk digital printing, offset, advertising,<br/>sablon, dan print shop.</span></div></div>
    <div class="hero-visual"><img src="/images/printing/offset-press.jpg" alt="Mesin cetak offset di lantai produksi percetakan" width="1400" height="1800" fetchpriority="high"/><div class="photo-shade"></div><span class="photo-label micro">BUILT FOR PRINTING.<br/>MADE FOR YOUR BUSINESS.</span><div class="image-index"><span>01 / OPERASIONAL</span><ArrowUpRight :size="28" :stroke-width="1"/></div><div class="image-caption"><span class="micro">MAKE IT EASY</span><p>Biar sistem yang<br/>menghubungkan.</p></div><span class="blue-block"></span></div>
    <div class="hero-baseline"><span>GRAFIKA PRO / SISTEM POS & PRODUKSI</span><span>ORDER <b>·</b> PRODUCTION <b>·</b> STOCK <b>·</b> REPORT</span><span>SCROLL TO EXPLORE ↓</span></div>
  </section>
  <section class="intro-section wrap"><div class="section-top"><p class="eyebrow">01 — PERSPEKTIF BARU</p><span class="micro">SATU PESANAN. BANYAK PROSES.</span></div><div class="split editorial-intro"><h2>Percetakan<br/>bukan cuma<br/>soal <em>cetak.</em></h2><div class="intro-copy"><p class="lead">Di balik satu pesanan, ada banyak hal yang harus tetap sinkron.</p><p>Nota di meja kasir. Status di grup chat. Stok di catatan gudang. Ketika informasi tersebar, pekerjaan sederhana pun harus ditanyakan berulang kali.</p><RouterLink class="text-link" to="/solusi">Saatnya bekerja lebih terhubung <ArrowUpRight :size="20"/></RouterLink></div></div><div class="pillar-grid"><article v-for="(pillar, i) in pillars" :key="pillar.name"><div class="pillar-top"><component :is="pillar.icon" :size="25" :stroke-width="1.25"/><span class="micro">0{{ i + 1 }}</span></div><h3>{{ pillar.name }}</h3><p>{{ pillar.text }}</p></article></div></section>
  <section class="campaign"><img src="/images/printing/offset-press.jpg" alt="Detail mesin dan alur kerja percetakan" loading="lazy" width="1400" height="1800"/><div class="wrap campaign-content"><p class="eyebrow">DARI NOTA HINGGA PRODUKSI</p><h2>Kerja tim nggak<br/>harus saling<br/><span class="highlight">tunggu.</span></h2><div class="campaign-note"><p>Setiap orang tahu apa yang harus dikerjakan, tanpa perlu menunggu instruksi terus-menerus.</p><RouterLink to="/cara-kerja" class="text-link">Kenali alurnya <ArrowUpRight :size="20"/></RouterLink></div><span class="micro">ORDER · PRODUCTION · STOCK · REPORT</span></div></section>
  <section class="wrap section-space"><div class="section-top"><p class="eyebrow">02 — SISTEM YANG IKUT BERTUMBUH</p><RouterLink class="text-link" to="/fitur">Semua Fitur <ArrowUpRight :size="19"/></RouterLink></div><div class="split"><h2>Mulai dari kebutuhan.<br/>Bukan kerumitan.</h2><p class="lead narrow">Fondasi yang lengkap. Modul tambahan yang bisa mengikuti tantangan percetakan Anda.</p></div><div class="module-preview"><RouterLink v-for="(item,i) in [{title:'Fondasi operasional',name:'Modul Inti',copy:'Kasir, produk & HPP, pelanggan, bahan, dan laporan keuangan.',hash:'inti'},{title:'Alur kerja lebih terhubung',name:'Pack Operasional',copy:'Gudang, Produksi, SDM, hingga Vendor. Pilih yang dibutuhkan.',hash:'gudang'},{title:'Baca usaha Anda sendiri',name:'AI Tutor & Analis',copy:'Panduan penggunaan dan pemahaman data dalam satu sistem.',hash:'ai'}]" :key="item.name" :to="'/fitur#'+item.hash"><span class="micro">0{{i+1}} / {{item.title}}</span><h3>{{item.name}}</h3><p>{{item.copy}}</p><ArrowUpRight :size="25" :stroke-width="1.25"/></RouterLink></div></section>
  <section class="service-strip"><div class="wrap split"><div><p class="eyebrow">BUKAN SEKADAR APLIKASI</p><h2>Terima beres.<br/>Sistem langsung jalan.</h2></div><div><p class="lead">Dari penataan data sampai tim terbiasa. Kami mendampingi prosesnya.</p><ul class="check-list"><li>Penataan produk, harga, dan data awal</li><li>Pelatihan bertahap sesuai peran tim</li><li>Server, backup harian, dan pembaruan sistem</li></ul><RouterLink class="text-link" to="/cara-kerja#implementasi">Lihat proses implementasi <ArrowUpRight :size="20"/></RouterLink></div></div></section>
  <CtaSection/>
</template>
