<script setup lang="ts">
import { ref } from 'vue'
import { Check, ArrowUpRight, Download } from 'lucide-vue-next'
import PageHeading from '../components/PageHeading.vue'
import CtaSection from '../components/CtaSection.vue'
import { plans,addons,rupiah } from '../data/pricing'
import { catalogUrl } from '../data/site'
const billing=ref<'annual'|'monthly'>('annual')
</script>
<template><PageHeading label="PAKET & HARGA 2026" number="04 / INVESTASI" title="Pas untuk kebutuhan." accent="Siap untuk bertumbuh." description="Fondasi lengkap di setiap paket. Pilih modul dan jumlah loket sesuai kebutuhan percetakan Anda. Server, backup harian, dan pembaruan sudah termasuk."/>
<section class="wrap"><div class="billing-bar"><div class="billing-toggle" role="group" aria-label="Periode pembayaran"><button @click="billing='annual'" :class="{active:billing==='annual'}" :aria-pressed="billing==='annual'">Tahunan · hemat ±20%</button><button @click="billing='monthly'" :class="{active:billing==='monthly'}" :aria-pressed="billing==='monthly'">Bulanan</button></div><p>Harga dalam Rupiah, belum termasuk PPN.</p></div><div class="pricing-grid"><article v-for="plan in plans" :key="plan.name" :class="['price-card',{featured:plan.featured}]"><p class="eyebrow">{{plan.featured ? 'OPERASIONAL TERINTEGRASI' : 'GRAFIKA PRO / 2026'}}</p><h2>{{plan.name}}</h2><p class="price-desc">{{plan.tagline}}</p><div aria-live="polite"><div class="price">{{rupiah(plan[billing])}}</div><span class="price-unit">/ {{billing==='annual'?'tahun · dibayar di muka':'bulan'}}</span></div><div class="setup-price">Program Penataan <strong>{{rupiah(plan.setup)}}</strong><br/>Sekali di awal, terpisah dari langganan.</div><ul><li v-for="feature in plan.features" :key="feature"><Check :size="13"/>{{feature}}</li></ul><RouterLink :to="{path:'/kontak',query:{paket:plan.name}}" class="button">Konsultasi {{plan.name}}<ArrowUpRight :size="17"/></RouterLink></article></div><p class="notice">Tidak ada biaya lisensi di muka. Program Penataan tetap dibayar sekali di awal untuk audit alur kerja, penataan data, pelatihan, dan pendampingan. AI Analis merupakan tambahan opsional Rp4.000.000/tahun.</p></section>
<section class="pricing-details wrap"><p class="eyebrow">BANDINGKAN DENGAN JELAS</p><h2>Yang Anda dapatkan.</h2><div class="table-wrap" tabindex="0" aria-label="Tabel perbandingan paket, geser horizontal pada layar kecil"><table class="data-table"><caption class="screen-reader-only">Perbandingan isi empat paket Grafika Pro</caption><thead><tr><th scope="col">Cakupan</th><th v-for="p in plans" :key="p.name" scope="col">{{p.name}}</th></tr></thead><tbody><tr><th scope="row">Modul Inti & AI Tutor</th><td v-for="p in plans" :key="p.name">Termasuk</td></tr><tr><th scope="row">Pack tambahan</th><td v-for="p in plans" :key="p.name">{{p.packs}}</td></tr><tr><th scope="row">Loket deskprint</th><td v-for="p in plans" :key="p.name">{{p.desks}}</td></tr><tr><th scope="row">Penyesuaian / bulan</th><td v-for="p in plans" :key="p.name">{{p.tweaks}}</td></tr><tr><th scope="row">Antrian & papan tampilan</th><td v-for="p in plans" :key="p.name">{{p.desks>=2?'Termasuk':'Belum termasuk'}}</td></tr><tr><th scope="row">Pengguna & transaksi</th><td v-for="p in plans" :key="p.name">Tidak dibatasi</td></tr></tbody></table></div></section>
<section class="wrap pricing-details" style="padding-top:0"><div class="section-top"><h2>Tambah yang dibutuhkan.</h2><a :href="catalogUrl" class="text-link" target="_blank" rel="noopener">Katalog lengkap <Download :size="17"/></a></div><p class="lead">Pack dapat ditambahkan ke Modul Inti. Harga berikut per tahun, di luar biaya Modul Inti dan penataan.</p><div class="addon-grid"><article v-for="item in addons" :key="item[0]"><h3>{{item[0]}}</h3><p>{{item[2]}}</p><strong>+ {{rupiah(item[1])}}<span class="price-unit"> / tahun</span></strong></article></div></section>
<section class="loyalty"><div class="wrap"><p class="eyebrow">HARGA SETIA</p><h2>Makin lama bersama.<br/>Makin ringan biayanya.</h2><p>Tahun 1–2 mengikuti harga katalog. Tahun 3–4 mendapat potongan tenor 10%, dan mulai tahun ke-5 mendapat potongan 20%. Berlaku juga pada tarif bulanan.</p><div class="notice">Kredit referensi dan prabayar dua tahun memiliki ketentuan tersendiri. Total potongan maksimal 30%; paket Mulai maksimal 20% dan tidak bertumpuk. Program Penataan tidak mendapat diskon. Lihat rincian dan tarif pembulatan di katalog.</div><a :href="catalogUrl" target="_blank" rel="noopener" class="text-link" style="margin-top:20px">Baca ketentuan lengkap <ArrowUpRight :size="18"/></a></div></section><CtaSection/></template>
